# file_encryptor.py
from cryptography.fernet import Fernet 
import os 

def encrypt_files_in_directory(directory, key_file):
    """
    Scans a directory and encrypts all files found using a provided key.
    """
    targets = []

    # Walk through the directory and collect all filenames
    for _, _, files in os.walk(directory):
        targets.extend(files)  
    
    print("Files to encrypt:", targets)

    # Load the encryption key from the specified file
    # The key must be the one generated by Fernet.generate_key()
    with open(key_file, 'rb') as file:
        key = file.read()

    # Initialize the Fernet cipher suite with the loaded key
    cipher_suite = Fernet(key)

    # Iterate through each file and apply encryption
    for target in targets:
        file_path = os.path.join(directory, target)
        
        # Read the original content of the file in binary mode
        with open(file_path, 'rb') as f:
            content = f.read()
            
        # Encrypt the data
        encrypted_content = cipher_suite.encrypt(content)

        # Overwrite the original file with the encrypted binary data
        with open(file_path, 'wb') as f_out:
            f_out.write(encrypted_content)

if __name__ == "__main__":
    # Configuration: specify the target folder and the key file location
    target_directory = 'targets'
    key_storage = 'key.txt'
    
    # Check if the directory exists before attempting encryption
    if os.path.exists(target_directory):
        encrypt_files_in_directory(target_directory, key_storage)
        print("Encryption process completed.")
    else:
        print(f"Error: The directory '{target_directory}' does not exist.")
